# Generated by Django 5.1.4 on 2024-12-31 17:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="The identification of the code system that defines the meaning of the symbol in the code.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the system - if relevant",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Symbol in syntax defined by the system",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        blank=True,
                        help_text="A representation of the meaning of the code in the system, following the rules of the system.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "valueset",
                    models.CharField(
                        choices=[
                            ("UKCore-HumanLanguage", "Uk Core Human Language"),
                            ("UKCoreMedicationForm", "Uk Core Medication Form"),
                            ("UKCoreMedicationCode", "Uk Core Medication Code"),
                            ("ObservationCategoryCodes", "Observation Category Code"),
                            ("UKCoreObservationType", "Uk Core Observation Type"),
                            ("UKCoreSpecimenType", "Uk Core Specimen Type"),
                            (
                                "FHIRSpecimenCollectionMethod",
                                "Fhir Specimen Collection Method",
                            ),
                            ("UKCoreSpecimenBodySite", "Uk Core Specimen Body Site"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usual", "Usual"),
                            ("official", "Official"),
                            ("temp", "Temp"),
                            ("secondary", "Secondary"),
                            ("old", "Old"),
                        ],
                        help_text="The purpose of this identifier.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "system",
                    models.URLField(
                        choices=[
                            (
                                "https://fhir.nhs.uk/Id/ods-organization-code",
                                "Ods Organisation Code",
                            ),
                            ("https://fhir.nhs.uk/Id/ods-site-code", "Ods Site Code"),
                            ("https://fhir.nhs.uk/Id/nhs-number", "Nhs Number"),
                            (
                                "https://fhir.hl7.org.uk/Id/gmc-number",
                                "General Medical Council Registration Number",
                            ),
                            (
                                "https://fhir.hl7.org.uk/Id/gphc-number",
                                "General Pharmaceutical Council Registration Number",
                            ),
                            (
                                "https://fhir.hl7.org.uk/Id/nmc-number",
                                "Nurses Midwives Health Visitors Council Registration Number",
                            ),
                            (
                                "https://fhir.hl7.org.uk/Id/hcpc-number",
                                "Healthcare Professions Registration Number",
                            ),
                            ("https://fhir.nhs.uk/Id/sds-user-id", "Spine"),
                            ("https://tools.ietf.org/html/rfc4122", "Uuid"),
                        ],
                        help_text="Establishes the namespace for the value - that is, a URL that describes a set values that are unique.",
                        max_length=64,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The portion of the identifier typically relevant to the user and which is unique within the context of the system."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usual", "Usual"),
                            ("official", "Official"),
                            ("temp", "Temp"),
                            ("nickname", "Nickname"),
                            ("anonymous", "Anonymous"),
                            ("old", "Old"),
                            ("maiden", "Maiden"),
                        ],
                        help_text="The purpose of this identifier.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "family",
                    models.TextField(
                        blank=True,
                        help_text="Family name (often called 'Surname').",
                        null=True,
                    ),
                ),
                (
                    "given",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="Given names (not always 'first'). Includes middle names.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "prefix",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="Part of the name that is acquired as a title due to academic, legal, employment or nobility status, etc. and that appears at the start of the name.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "suffix",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="Part of the name that is acquired as a title due to academic, legal, employment or nobility status, etc. and that appears at the end of the name.",
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="A name associated with the organization."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes.",
                        max_length=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "batchLotNumber",
                    models.CharField(
                        blank=True,
                        help_text="Identifier assigned to batch",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "batchExpirationDate",
                    models.DateTimeField(
                        blank=True, help_text="When batch will expire", null=True
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        help_text="Codes that identify this medication",
                        limit_choices_to={"valueset": "UKCoreMedicationCode"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicationcode",
                        to="api.concept",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        help_text="Codes that identify this medication",
                        limit_choices_to={"valueset": "UKCoreMedicationForm"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicationform",
                        to="api.concept",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("preliminary", "Preliminary"),
                            ("final", "Final"),
                            ("amended", "Amended"),
                        ],
                        help_text="The status of the result value.",
                        max_length=16,
                    ),
                ),
                (
                    "effectiveDateTime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Clinically relevant time/time-period for observation",
                        null=True,
                    ),
                ),
                (
                    "effectiveInstant",
                    models.DateTimeField(
                        blank=True,
                        help_text="Clinically relevant time/time-period for observation",
                        null=True,
                    ),
                ),
                ("valueQuantity", models.JSONField(blank=True, null=True)),
                (
                    "category",
                    models.ManyToManyField(
                        help_text="A code that classifies the general type of observation being made.",
                        limit_choices_to={"valueset": "ObservationCategoryCodes"},
                        related_name="observationcategory",
                        to="api.concept",
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        help_text="Type of observation (code / type)",
                        limit_choices_to={"valueset": "UKCoreObservationType"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observationcode",
                        to="api.concept",
                    ),
                ),
                ("hasMember", models.ManyToManyField(to="api.observation")),
                (
                    "performer",
                    models.ManyToManyField(
                        help_text="Who is responsible for the observation",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObservationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valueQuantity", models.JSONField(blank=True, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        limit_choices_to={"valueset": "UKCoreObservationType"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.concept",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.observation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationAddress",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("billing", "Billing"),
                        ],
                        help_text="The purpose of this address.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postal", "Postal"),
                            ("physical", "Physical"),
                            ("both", "Both"),
                        ],
                        help_text="Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "line",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="This component contains the house number, apartment number, street name, street direction, P.O. Box number, delivery hints, and similar address information.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        blank=True,
                        help_text="The name of the city, town, suburb, village or other community or delivery center.",
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.TextField(
                        blank=True,
                        help_text="The name of the administrative area (county).",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        blank=True,
                        help_text="Sub-unit of a country with limited sovereignty in a federally organized country. A code may be used if codes are in common use (e.g. US 2 letter state codes).",
                        null=True,
                    ),
                ),
                (
                    "postalCode",
                    models.TextField(
                        blank=True,
                        help_text="A postal code designating a region defined by the postal service.",
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Country - a nation as commonly understood or generally accepted.",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationContactPoint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("fax", "Fax"),
                            ("email", "Email"),
                            ("pager", "Pager"),
                            ("url", "Url"),
                            ("sms", "Sms"),
                            ("other", "Other"),
                        ],
                        help_text="Telecommunications form for contact point - what communications system is required to make use of the contact.",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="The actual contact point details."),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("mobile", "Mobile"),
                        ],
                        help_text="purpose of this contact point",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Specify preferred order of use (1 = highest)",
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "birthDate",
                    models.DateField(
                        blank=True,
                        help_text="The date of birth for the individual.",
                        null=True,
                    ),
                ),
                (
                    "communication",
                    models.ManyToManyField(
                        limit_choices_to={"system": "UKCore-HumanLanguage"},
                        to="api.concept",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="observation",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Who and/or what the observation is about",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.patient",
            ),
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("billing", "Billing"),
                        ],
                        help_text="The purpose of this address.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postal", "Postal"),
                            ("physical", "Physical"),
                            ("both", "Both"),
                        ],
                        help_text="Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "line",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="This component contains the house number, apartment number, street name, street direction, P.O. Box number, delivery hints, and similar address information.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        blank=True,
                        help_text="The name of the city, town, suburb, village or other community or delivery center.",
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.TextField(
                        blank=True,
                        help_text="The name of the administrative area (county).",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        blank=True,
                        help_text="Sub-unit of a country with limited sovereignty in a federally organized country. A code may be used if codes are in common use (e.g. US 2 letter state codes).",
                        null=True,
                    ),
                ),
                (
                    "postalCode",
                    models.TextField(
                        blank=True,
                        help_text="A postal code designating a region defined by the postal service.",
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Country - a nation as commonly understood or generally accepted.",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="A name associated with the contact person.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientTelecom",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("fax", "Fax"),
                            ("email", "Email"),
                            ("pager", "Pager"),
                            ("url", "Url"),
                            ("sms", "Sms"),
                            ("other", "Other"),
                        ],
                        help_text="Telecommunications form for contact point - what communications system is required to make use of the contact.",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="The actual contact point details."),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("mobile", "Mobile"),
                        ],
                        help_text="purpose of this contact point",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Specify preferred order of use (1 = highest)",
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PractitionerAddress",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("billing", "Billing"),
                        ],
                        help_text="The purpose of this address.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postal", "Postal"),
                            ("physical", "Physical"),
                            ("both", "Both"),
                        ],
                        help_text="Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "line",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="This component contains the house number, apartment number, street name, street direction, P.O. Box number, delivery hints, and similar address information.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        blank=True,
                        help_text="The name of the city, town, suburb, village or other community or delivery center.",
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.TextField(
                        blank=True,
                        help_text="The name of the administrative area (county).",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        blank=True,
                        help_text="Sub-unit of a country with limited sovereignty in a federally organized country. A code may be used if codes are in common use (e.g. US 2 letter state codes).",
                        null=True,
                    ),
                ),
                (
                    "postalCode",
                    models.TextField(
                        blank=True,
                        help_text="A postal code designating a region defined by the postal service.",
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Country - a nation as commonly understood or generally accepted.",
                        null=True,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PractitionerTelecom",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("fax", "Fax"),
                            ("email", "Email"),
                            ("pager", "Pager"),
                            ("url", "Url"),
                            ("sms", "Sms"),
                            ("other", "Other"),
                        ],
                        help_text="Telecommunications form for contact point - what communications system is required to make use of the contact.",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="The actual contact point details."),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("mobile", "Mobile"),
                        ],
                        help_text="purpose of this contact point",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Specify preferred order of use (1 = highest)",
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("unsatisfactory", "Unsatisfactory"),
                            ("entered-in-error", "Entered In Error"),
                        ],
                        help_text="The availability of the specimen.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "receivedTime",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when specimen was received for processing.",
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the specimen came from.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The kind of material that forms the specimen.",
                        limit_choices_to={"valueset": "UKCoreSpecimenType"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.concept",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecimenComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collectedDateTime", models.DateTimeField(blank=True, null=True)),
                (
                    "bodySite",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"valueset": "UKCoreSpecimenBodySite"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimencomponentbodysite",
                        to="api.concept",
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"valueset": "FHIRSpecimenCollectionMethod"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.concept",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.specimen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        limit_choices_to={
                            "system": ["https://tools.ietf.org/html/rfc4122"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.observation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="OrganizationIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={
                            "system": [
                                "https://fhir.nhs.uk/Id/ods-site-code",
                                "https://fhir.nhs.uk/Id/ods-organization-code",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to=["https://fhir.nhs.uk/Id/nhs-number"],
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="PractitionerIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        limit_choices_to={
                            "system": [
                                "https://fhir.hl7.org.uk/Id/gmc-number",
                                "https://fhir.hl7.org.uk/Id/gphc-number",
                                "https://fhir.hl7.org.uk/Id/hcpc-number",
                                "https://fhir.hl7.org.uk/Id/nmc-number",
                                "https://fhir.nhs.uk/Id/sds-user-id",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="PatientName",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.name",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="A name associated with the contact person.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.name",),
        ),
        migrations.CreateModel(
            name="PractitionerName",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.name",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.name",),
        ),
    ]
