# Generated by Django 5.1.4 on 2024-12-30 19:50
import json
import os.path

from django.db import migrations
from django.db import models

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def load_row(txt: str) -> list[str]:
    return json.loads("[" + txt + "]")


def load_concepts(apps, schema_editor):
    Concept = apps.get_model("api", "Concept")
    header, *rows = map(load_row, open(f"{BASE_DIR}/concepts.csv").readlines())

    for row in rows:
        Concept.objects.create(**dict(zip(header, row)))


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="The identification of the code system that defines the meaning of the symbol in the code.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the system - if relevant",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Symbol in syntax defined by the system",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        blank=True,
                        help_text="A representation of the meaning of the code in the system, following the rules of the system.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "valueset",
                    models.CharField(
                        choices=[
                            ("UKCore-HumanLanguage", "Uk Core Human Language"),
                            ("UKCoreMedicationForm", "Uk Core Medication Form"),
                            ("UKCoreMedicationCode", "Uk Core Medication Code"),
                            ("ObservationCategoryCodes", "Observation Category Code"),
                            ("UKCoreObservationType", "Uk Core Observation Type"),
                            ("UKCoreSpecimenType", "Uk Core Specimen Type"),
                            (
                                "FHIRSpecimenCollectionMethod",
                                "Fhir Specimen Collection Method",
                            ),
                            ("UKCoreSpecimenBodySite", "Uk Core Specimen Body Site"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.RunPython(load_concepts, migrations.RunPython.noop),
    ]
