# Generated by Django 5.1.4 on 2024-12-30 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record is still in active use",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="identifier",
            name="system",
            field=models.URLField(
                choices=[
                    (
                        "https://fhir.nhs.uk/Id/ods-organization-code",
                        "Ods Organisation Code",
                    ),
                    ("https://fhir.nhs.uk/Id/ods-site-code", "Ods Site Code"),
                    ("https://fhir.nhs.uk/Id/nhs-number", "Nhs Number"),
                    (
                        "https://fhir.hl7.org.uk/Id/gmc-number",
                        "General Medical Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/gphc-number",
                        "General Pharmaceutical Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/nmc-number",
                        "Nurses Midwives Health Visitors Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/hcpc-number",
                        "Healthcare Professions Registration Number",
                    ),
                ],
                help_text="Establishes the namespace for the value - that is, a URL that describes a set values that are unique.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PractitionerIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="PractitionerName",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.name",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.name",),
        ),
        migrations.CreateModel(
            name="PractitionerTelecom",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("fax", "Fax"),
                            ("email", "Email"),
                            ("pager", "Pager"),
                            ("url", "Url"),
                            ("sms", "Sms"),
                            ("other", "Other"),
                        ],
                        help_text="Telecommunications form for contact point - what communications system is required to make use of the contact.",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="The actual contact point details."),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("mobile", "Mobile"),
                        ],
                        help_text="purpose of this contact point",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Specify preferred order of use (1 = highest)",
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the contact point was/is in use",
                        null=True,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
