# Generated by Django 5.1.4 on 2024-12-30 19:50
import json
import os.path

from django.db import migrations

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def load_row(txt: str) -> list[str]:
    return json.loads("[" + txt + "]")


def load_concepts(apps, schema_editor):
    Concept = apps.get_model("api", "Concept")
    header, *rows = map(load_row, open(f"{BASE_DIR}/concepts.csv").readlines())

    for row in rows:
        Concept.objects.create(**dict(zip(header, row)))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_concepts, migrations.RunPython.noop),
    ]
