# Generated by Django 5.1.4 on 2024-12-30 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_practitioner_alter_identifier_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
