# Generated by Django 5.1.4 on 2024-12-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_load_concepts"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="bodySite",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"valueset": "UKCoreSpecimenBodySite"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specimenbodysite",
                to="api.concept",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="collectedDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specimen",
            name="collector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="method",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"valueset": "FHIRSpecimenCollectionMethod"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specimenmethod",
                to="api.concept",
            ),
        ),
        migrations.DeleteModel(
            name="SpecimenComponent",
        ),
    ]
