# Generated by Django 5.1.4 on 2024-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_observation_performer_observation_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="subject",
        ),
        migrations.AddField(
            model_name="observation",
            name="subject",
            field=models.ManyToManyField(
                help_text="Who and/or what the observation is about", to="api.patient"
            ),
        ),
    ]
