# Generated by Django 5.1.4 on 2024-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_organization_id_alter_practitioner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="system",
            field=models.URLField(
                choices=[
                    (
                        "https://fhir.nhs.uk/Id/ods-organization-code",
                        "Ods Organisation Code",
                    ),
                    ("https://fhir.nhs.uk/Id/ods-site-code", "Ods Site Code"),
                    ("https://fhir.nhs.uk/Id/nhs-number", "Nhs Number"),
                    (
                        "https://fhir.hl7.org.uk/Id/gmc-number",
                        "General Medical Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/gphc-number",
                        "General Pharmaceutical Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/nmc-number",
                        "Nurses Midwives Health Visitors Council Registration Number",
                    ),
                    (
                        "https://fhir.hl7.org.uk/Id/hcpc-number",
                        "Healthcare Professions Registration Number",
                    ),
                    ("https://fhir.nhs.uk/Id/sds-user-id", "Spine"),
                ],
                help_text="Establishes the namespace for the value - that is, a URL that describes a set values that are unique.",
                max_length=64,
            ),
        ),
    ]
