# Generated by Django 5.1.4 on 2024-12-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_observation_subject_observation_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="effectiveDateTime",
            field=models.DateTimeField(
                blank=True,
                help_text="Clinically relevant time/time-period for observation",
                null=True,
            ),
        ),
    ]
