# Generated by Django 5.1.4 on 2024-12-30 17:15

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_identifier_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerAddress",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time period when the record was/is in use",
                        null=True,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("billing", "Billing"),
                        ],
                        help_text="The purpose of this address.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postal", "Postal"),
                            ("physical", "Physical"),
                            ("both", "Both"),
                        ],
                        help_text="Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "line",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="This component contains the house number, apartment number, street name, street direction, P.O. Box number, delivery hints, and similar address information.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        blank=True,
                        help_text="The name of the city, town, suburb, village or other community or delivery center.",
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.TextField(
                        blank=True,
                        help_text="The name of the administrative area (county).",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        blank=True,
                        help_text="Sub-unit of a country with limited sovereignty in a federally organized country. A code may be used if codes are in common use (e.g. US 2 letter state codes).",
                        null=True,
                    ),
                ),
                (
                    "postalCode",
                    models.TextField(
                        blank=True,
                        help_text="A postal code designating a region defined by the postal service.",
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Country - a nation as commonly understood or generally accepted.",
                        null=True,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.practitioner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
