# Generated by Django 5.1.4 on 2024-12-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_practitioneraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitioner",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                help_text="Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes.",
                max_length=8,
                null=True,
            ),
        ),
    ]
