# Generated by Django 5.1.4 on 2024-12-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_practitioner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationidentifier',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'system': ['https://fhir.nhs.uk/Id/ods-site-code', 'https://fhir.nhs.uk/Id/ods-organization-code']}, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
    ]
