# Generated by Django 5.1.4 on 2024-12-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_organizationidentifier_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioneridentifier',
            name='practitioner',
            field=models.ForeignKey(limit_choices_to={'system': ['https://fhir.hl7.org.uk/Id/gmc-number', 'https://fhir.hl7.org.uk/Id/gphc-number', 'https://fhir.hl7.org.uk/Id/hcpc-number', 'https://fhir.hl7.org.uk/Id/nmc-number', 'https://fhir.nhs.uk/Id/sds-user-id']}, on_delete=django.db.models.deletion.CASCADE, to='api.practitioner'),
        ),
    ]
